export const RESTAURANTS = [
  {
    id: 1,
    name: "برجر هاوس",
    category: "برجر",
    rating: 4.7,
    eta: "25-35",
    image: "🍔",
    cuisine: "أمريكي",
    minOrder: 15,
    isOpen: true,
  },
  {
    id: 2,
    name: "بيتزا بلانيت",
    category: "بيتزا",
    rating: 4.5,
    eta: "30-40",
    image: "🍕",
    cuisine: "إيطالي",
    minOrder: 20,
    isOpen: true,
  },
  {
    id: 3,
    name: "شاورما ستار",
    category: "شرقي",
    rating: 4.8,
    eta: "20-30",
    image: "🌯",
    cuisine: "عربي",
    minOrder: 10,
    isOpen: true,
  },
  {
    id: 4,
    name: "سوشي تايم",
    category: "سوشي",
    rating: 4.6,
    eta: "40-50",
    image: "🍣",
    cuisine: "ياباني",
    minOrder: 30,
    isOpen: false,
  },
  {
    id: 5,
    name: "باستا فيلا",
    category: "باستا",
    rating: 4.4,
    eta: "30-45",
    image: "🍝",
    cuisine: "إيطالي",
    minOrder: 18,
    isOpen: true,
  },
  {
    id: 6,
    name: "تاكو لوكو",
    category: "مكسيكي",
    rating: 4.3,
    eta: "25-35",
    image: "🌮",
    cuisine: "مكسيكي",
    minOrder: 12,
    isOpen: true,
  },
];

export const MENUS = {
  1: [
    {
      id: 101,
      name: "برجر كلاسيك",
      desc: "لحم بقري، جبنة شيدر، خس، طماطم",
      price: 18,
      image: "🍔",
      available: true,
      category: "برجر",
    },
    {
      id: 102,
      name: "برجر دبل",
      desc: "قرصان لحم مع صوص خاص",
      price: 25,
      image: "🍔",
      available: true,
      category: "برجر",
    },
    {
      id: 103,
      name: "تشيكن برجر",
      desc: "دجاج مقرمش مع صوص رانش",
      price: 20,
      image: "🍗",
      available: true,
      category: "دجاج",
    },
    {
      id: 104,
      name: "بطاطا مقلية",
      desc: "بطاطا ذهبية مقرمشة",
      price: 8,
      image: "🍟",
      available: true,
      category: "جانبي",
    },
    {
      id: 105,
      name: "كول سلو",
      desc: "سلطة ملفوف طازجة",
      price: 6,
      image: "🥗",
      available: false,
      category: "جانبي",
    },
  ],

  2: [
    {
      id: 201,
      name: "مارغريتا",
      desc: "صوص طماطم، جبنة موزاريلا، ريحان",
      price: 22,
      image: "🍕",
      available: true,
      category: "بيتزا",
    },
    {
      id: 202,
      name: "بيبيروني",
      desc: "بيبيروني، جبنة، صوص خاص",
      price: 28,
      image: "🍕",
      available: true,
      category: "بيتزا",
    },
    {
      id: 203,
      name: "فور سيزونز",
      desc: "أربع نكهات في بيتزا واحدة",
      price: 35,
      image: "🍕",
      available: true,
      category: "بيتزا",
    },
    {
      id: 204,
      name: "عصير برتقال",
      desc: "عصير طازج",
      price: 7,
      image: "🍊",
      available: true,
      category: "مشروبات",
    },
  ],

  3: [
    {
      id: 301,
      name: "شاورما دجاج",
      desc: "دجاج متبل مع توم وبطاطا",
      price: 12,
      image: "🌯",
      available: true,
      category: "شاورما",
    },
    {
      id: 302,
      name: "شاورما لحم",
      desc: "لحم عجل مع صوص طحينة",
      price: 15,
      image: "🌯",
      available: true,
      category: "شاورما",
    },
    {
      id: 303,
      name: "فلافل",
      desc: "فلافل هش مع سلطة وطحينة",
      price: 9,
      image: "🧆",
      available: true,
      category: "فلافل",
    },
    {
      id: 304,
      name: "حمص",
      desc: "حمص طازج بزيت الزيتون",
      price: 7,
      image: "🫘",
      available: true,
      category: "مقبلات",
    },
  ],

  5: [
    {
      id: 501,
      name: "باستا كربونارا",
      desc: "بيض، جبنة بارميزان، لحم مقدد",
      price: 24,
      image: "🍝",
      available: true,
      category: "باستا",
    },
    {
      id: 502,
      name: "باستا بولونيز",
      desc: "لحم مفروم بصوص طماطم",
      price: 22,
      image: "🍝",
      available: true,
      category: "باستا",
    },
    {
      id: 503,
      name: "ريزوتو",
      desc: "أرز إيطالي بالفطر",
      price: 26,
      image: "🍚",
      available: true,
      category: "أرز",
    },
  ],

  6: [
    {
      id: 601,
      name: "تاكو دجاج",
      desc: "دجاج، سالسا، جواكامولي",
      price: 14,
      image: "🌮",
      available: true,
      category: "تاكو",
    },
    {
      id: 602,
      name: "بوريتو لحم",
      desc: "لحم، أرز، فاصوليا، جبنة",
      price: 18,
      image: "🌯",
      available: true,
      category: "بوريتو",
    },
    {
      id: 603,
      name: "ناتشوز",
      desc: "رقائق مع صوص وجبنة",
      price: 12,
      image: "🫔",
      available: true,
      category: "مشتركات",
    },
  ],
};

export const MOCK_USERS = [
  {
    id: 1,
    email: "customer@test.com",
    password: "123",
    name: "محمد العميل",
    role: "customer",
    phone: "0599000001",
    address: "رام الله، شارع الإرسال",
  },
  {
    id: 2,
    email: "admin@test.com",
    password: "123",
    name: "أمير الإداري",
    role: "admin",
    phone: "0599000002",
    address: "",
  },
  {
    id: 3,
    email: "driver@test.com",
    password: "123",
    name: "كريم السائق",
    role: "driver",
    phone: "0599000003",
    address: "",
  },
  {
    id: 4,
    email: "restaurant@test.com",
    password: "123",
    name: "مطعم برجر هاوس",
    role: "restaurant",
    phone: "0599000004",
    restaurantId: 1,
  },
];

export const STATUS_LABELS = {
  confirmed: {
    label: "تم الطلب",
    color: "#3b82f6",
    icon: "✅",
  },

  preparing: {
    label: "جاري التحضير",
    color: "#f59e0b",
    icon: "👨‍🍳",
  },

  ready: {
    label: "جاهز للاستلام",
    color: "#8b5cf6",
    icon: "📦",
  },

  picked_up: {
    label: "في الطريق",
    color: "#f97316",
    icon: "🛵",
  },

  delivered: {
    label: "تم التوصيل",
    color: "#22c55e",
    icon: "🎉",
  },
};